#_________start git
source /data/data/com.termux/files/home/.myconf/alias/bassic.sh
source /data/data/com.termux/files/home/.myconf/alias/init.sh
source /data/data/com.termux/files/home/.myconf/bash/init.sh
source /data/data/com.termux/files/home/.myconf/bash/theme.sh
source /data/data/com.termux/files/home/.myconf/dir/dir.sh
source /data/data/com.termux/files/home/.myconf/dir/variable.sh
source /data/data/com.termux/files/home/.myconf/alias/auto/a.scss.sh
source /data/data/com.termux/files/home/.myconf/alias/auto/git.sh
source /data/data/com.termux/files/home/.myconf/alias/oh_my_bash/chmod.aliases.sh
source /data/data/com.termux/files/home/.myconf/alias/oh_my_bash/general.aliases.sh
source /data/data/com.termux/files/home/.myconf/alias/oh_my_bash/git.plugin.sh
source /data/data/com.termux/files/home/.myconf/alias/oh_my_bash/ls.aliases.sh
source /data/data/com.termux/files/home/.myconf/bash/completions/defaults.completion.sh
source /data/data/com.termux/files/home/.myconf/bash/completions/dirs.completion.sh
source /data/data/com.termux/files/home/.myconf/bash/completions/git.completion.sh
source /data/data/com.termux/files/home/.myconf/bash/completions/git.sh
source /data/data/com.termux/files/home/.myconf/bash/completions/hugo.sh
source /data/data/com.termux/files/home/.myconf/bash/completions/makefile.completion.sh
source /data/data/com.termux/files/home/.myconf/bash/completions/system.completion.sh
source /data/data/com.termux/files/home/.myconf/bash/termux/clipboard.sh
source /data/data/com.termux/files/home/.myconf/bash/ubuntu/dir.sh
source /data/data/com.termux/files/home/.myconf/bash/ubuntu/var.sh
source /data/data/com.termux/files/home/.myconf/git/alias/autossh.sh
source /data/data/com.termux/files/home/.myconf/git/alias/bassic.sh
source /data/data/com.termux/files/home/.myconf/git/alias/commit.sh
source /data/data/com.termux/files/home/.myconf/git/alias/gitflow.sh
source /data/data/com.termux/files/home/.myconf/git/alias/help.sh
source /data/data/com.termux/files/home/.myconf/git/alias/push.sh
source /data/data/com.termux/files/home/.myconf/git/alias/versioning.sh
source /data/data/com.termux/files/home/.myconf/git/func/fetch-pull.sh
source /data/data/com.termux/files/home/.myconf/git/func/versioning.sh
source /data/data/com.termux/files/home/.myconf/alias/app/git/autossh.sh
source /data/data/com.termux/files/home/.myconf/alias/app/git/bassic.sh
source /data/data/com.termux/files/home/.myconf/alias/app/git/commit.sh
source /data/data/com.termux/files/home/.myconf/alias/app/git/conflick.sh
source /data/data/com.termux/files/home/.myconf/alias/app/git/fetch.sh
source /data/data/com.termux/files/home/.myconf/alias/app/git/gitflow.sh
source /data/data/com.termux/files/home/.myconf/alias/app/git/help.sh
source /data/data/com.termux/files/home/.myconf/alias/app/git/muryp.sh
source /data/data/com.termux/files/home/.myconf/alias/app/git/push.sh
source /data/data/com.termux/files/home/.myconf/alias/app/hugo/alias.sh
source /data/data/com.termux/files/home/.myconf/alias/app/hugo/muryp.sh
source /data/data/com.termux/files/home/.myconf/alias/app/other/change-file-extention.sh
source /data/data/com.termux/files/home/.myconf/alias/app/other/fzf.sh
source /data/data/com.termux/files/home/.myconf/alias/app/sync/bassic.sh
source /data/data/com.termux/files/home/.myconf/alias/app/sync/muryp.sh
source /data/data/com.termux/files/home/.myconf/alias/app/tar/autobackup.sh
source /data/data/com.termux/files/home/.myconf/alias/app/tar/autorestore.sh
source /data/data/com.termux/files/home/.myconf/alias/app/tar/bassic.sh
source /data/data/com.termux/files/home/.myconf/alias/app/termux/bassic.sh
source /data/data/com.termux/files/home/.myconf/alias/app/termux/os.sh
source /data/data/com.termux/files/home/.myconf/alias/app/vim/bassic.sh
source /data/data/com.termux/files/home/.myconf/alias/app/vim/vimwiki.sh
#_________start git
