#_________start git
source /data/data/com.termux/files/home/.myconf/alias/app/hugo/alias.sh
source /data/data/com.termux/files/home/.myconf/alias/app/hugo/muryp.sh
source /data/data/com.termux/files/home/.myconf/alias/app/other/change-file-extention.sh
source /data/data/com.termux/files/home/.myconf/alias/app/other/fzf.sh
source /data/data/com.termux/files/home/.myconf/alias/app/sync/bassic.sh
source /data/data/com.termux/files/home/.myconf/alias/app/sync/muryp.sh
source /data/data/com.termux/files/home/.myconf/alias/app/tar/autobackup.sh
source /data/data/com.termux/files/home/.myconf/alias/app/tar/autorestore.sh
source /data/data/com.termux/files/home/.myconf/alias/app/tar/bassic.sh
source /data/data/com.termux/files/home/.myconf/alias/app/termux/bassic.sh
source /data/data/com.termux/files/home/.myconf/alias/app/termux/os.sh
source /data/data/com.termux/files/home/.myconf/alias/app/vim/bassic.sh
source /data/data/com.termux/files/home/.myconf/alias/app/vim/vimwiki.sh
source /data/data/com.termux/files/home/.myconf/alias/auto/a.scss.sh
source /data/data/com.termux/files/home/.myconf/alias/bassic.sh
source /data/data/com.termux/files/home/.myconf/dir/bassic.sh
source /data/data/com.termux/files/home/.myconf/dir/git.sh
source /data/data/com.termux/files/home/.myconf/dir/undo.sh
source /data/data/com.termux/files/home/.myconf/dir/variable.sh
source /data/data/com.termux/files/home/.myconf/fzf/cp.sh
source /data/data/com.termux/files/home/.myconf/fzf/dir.sh
source /data/data/com.termux/files/home/.myconf/fzf/mv.sh
source /data/data/com.termux/files/home/.myconf/fzf/rm.sh
source /data/data/com.termux/files/home/.myconf/fzf/style.sh
source /data/data/com.termux/files/home/.myconf/fzf/vim.sh
source /data/data/com.termux/files/home/.myconf/git/alias/autossh.sh
source /data/data/com.termux/files/home/.myconf/git/alias/bassic.sh
source /data/data/com.termux/files/home/.myconf/git/alias/commit.sh
source /data/data/com.termux/files/home/.myconf/git/alias/gitflow.sh
source /data/data/com.termux/files/home/.myconf/git/alias/help.sh
source /data/data/com.termux/files/home/.myconf/git/alias/push.sh
source /data/data/com.termux/files/home/.myconf/git/alias/versioning.sh
source /data/data/com.termux/files/home/.myconf/git/func/fetch-pull.sh
source /data/data/com.termux/files/home/.myconf/git/func/versioning.sh
#_________start git
