# dr=~/
# zzz=$dr/zzz
dc=$dr/.myconf
# db=$dc/bash
dssh=$dr.ssh
dw=$dr/web
dm=$dw/muryp-new
dvp=$dr.config/plugin
dv=$dvp/nvim-conf

alias dr='cd $dr'
alias zzz='cd $zzz'
alias dc='cd $dc'
alias db='cd $db'
alias dv='cd $dv'
alias dssh='cd $dssh'
alias dw='cd $dw'
alias dm='cd $dm'
alias dvc='cd $dvc'
alias dvp='cd $dvp'
