extern=~/storage/external-1
zzz=$extern/.zzz
dm=$zzz/web/muryp # default dir alias
dmi=$muryp/hosting/img/public
dms=$muryp/hosting/script/public
dc=$extern/config
db=$config/bash
dv=$config/nvim
ssh=$extern/.ssh
